### ISSUE TITLE
Erro ao tentar iniciar o app

### ISSUE THREAD

**Issue by hugodias** [braziljs/remote-control#8]
Ao tentar rodar o APP recebi o seguinte warning:

➜  remote-control git:(master) node app.js 
   info  - socket.io started
   warn  - error raised: Error: listen EACCES

Sabe o que pode ser ?

**Comment by jaydson** [comment]
Try with sudo:
sudo node app.js

**Comment by hugodias** [comment]
holy crap, so simple ;o Thank you @jaydson
